# Site settings
title: Hayden Wei
email: haidongrun#gmail.com
description: "My thougyts about Programming, Life, Technology."
baseurl: ""
url: "http://gnodiah.github.io/blog"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title/

github: 'https://github.com/Gnodiah/'
twitter: 'https://twitter.com/gnodiahwei'
