source "https://ruby.taobao.org"

gem 'rake'
gem 'rack'
gem 'jekyll', '~> 0.11.2'
gem 'rdiscount'
gem 'pygments.rb'
gem 'RedCloth'
gem 'haml'
gem 'compass'
gem 'rubypants'
gem 'rb-fsevent'
gem 'stringex'
gem 'liquid'
gem 'rake-minify'
gem 'sinatra'
